#!/usr/bin/env bash
#
# Copyright (c) 2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
BUILD_DIR="/opt/rapid"
export RTE_SDK="${BUILD_DIR}/dpdk"
export RTE_TARGET="build"
pushd ${BUILD_DIR}/samplevnf/VNFs/DPPD-PROX > /dev/null 2>&1
make -j`getconf _NPROCESSORS_ONLN`
cp ${BUILD_DIR}/samplevnf/VNFs/DPPD-PROX/build/app/prox ${BUILD_DIR}/prox
cp helper-scripts/rapid/check_prox_system_setup.sh ${BUILD_DIR}
cp helper-scripts/rapid/check-prox-system-setup.service ${BUILD_DIR}
cp helper-scripts/rapid/sharkproxlog.sh ${BUILD_DIR}
cp helper-scripts/rapid/deploycentostools.sh ${BUILD_DIR}
cp helper-scripts/rapid/rapid_rsa_key.pub ${BUILD_DIR}
popd > /dev/null 2>&1
