# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
{{ if ne .Values.prox.network "sriov-openness-vm" }}
{{ if .Values.prox.cnfs }}
{{- range .Values.prox.cnfs }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  {{ if ne $.Values.prox.network "sriov-openness-dpdk" }}
  annotations:
    k8s.v1.cni.cncf.io/networks: {{ $.Values.prox.network }}
  {{ end }}
  labels:
    release: {{ $.Release.Name }}
    app: {{ .name }}
spec:
  nodeName: {{ .nodeSelector_hostname }}
  containers:
  - name: {{ .name }}
    image: {{ $.Values.prox.controller_ip }}:5000/prox_slim:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args:
      - echo "Writing OVS device name";
        sed -ne '/hostname/p' /proc/1/task/1/mountinfo | awk -F '/' '{print "dev=\""substr($6,1,12)"\""}' > /root/parameters.lua;
        echo "Writing PCI address";
        echo "pci_address=os.getenv(\"PCIDEVICE_INTEL_COM_INTEL_SRIOV_DPDK\")" >> /root/parameters.lua;
        echo "done";
        sleep infinity;
    securityContext:
      privileged: true
      capabilities:
        add: ["IPC_LOCK", "NET_ADMIN"]
    volumeMounts:
    {{ if eq $.Values.prox.network "sriov-openness-dpdk" }}
    - mountPath: /sys/devices
      name: devices-dir
    {{ end }}
    - mountPath: /ovs
      name: shared-dir
    - mountPath: /dev/hugepages
      name: hugepages
    - mountPath: /data/templates
      name: prox-config
    resources:
      requests:
        hugepages-1Gi: 1Gi
        memory: 1Gi
        {{ if eq $.Values.prox.network "sriov-openness" }}
        intel.com/intel_sriov_netdevice: '1'
        {{ end }}
        {{ if eq $.Values.prox.network "sriov-openness-vm" }}
        intel.com/intel_sriov_vm: '1'
        {{ end }}
        {{ if eq $.Values.prox.network "sriov-openness-dpdk" }}
        intel.com/intel_sriov_dpdk: '1'
        {{ end }}
      limits:
        hugepages-1Gi: 1Gi
        {{ if eq $.Values.prox.network "sriov-openness" }}
        intel.com/intel_sriov_netdevice: '1'
        {{ end }}
        {{ if eq $.Values.prox.network "sriov-openness-vm" }}
        intel.com/intel_sriov_vm: '1'
        {{ end }}
        {{ if eq $.Values.prox.network "sriov-openness-dpdk" }}
        intel.com/intel_sriov_dpdk: '1'
        {{ end }}
  volumes:
  - name: devices-dir
    hostPath:
      path: /sys/devices/
  - name: shared-dir
    hostPath:
      path: /var/run/openvswitch/
  - name: hugepages
    emptyDir:
      medium: HugePages
  - name: prox-config
    configMap:
      name: swap-gen-config
  restartPolicy: Never
---
{{- end }}
{{ end }}
{{ end }}
